# Generated by Django 5.2.7 on 2025-10-29 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='busdata',
            options={'ordering': ['station_seq', 'plate_no'], 'verbose_name': '버스 데이터', 'verbose_name_plural': '버스 데이터들'},
        ),
    ]
