# Generated by Django 5.2.7 on 2025-10-29 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(max_length=20, verbose_name='노선 ID')),
                ('query_time', models.DateTimeField(verbose_name='쿼리 시간')),
                ('collection_date', models.DateField(db_index=True, verbose_name='수집 날짜')),
                ('result_code', models.IntegerField(default=0, verbose_name='결과 코드')),
                ('result_message', models.CharField(blank=True, max_length=200, verbose_name='결과 메시지')),
                ('is_error', models.BooleanField(default=False, verbose_name='오류 여부')),
                ('error_message', models.TextField(blank=True, verbose_name='오류 메시지')),
                ('is_skipped', models.BooleanField(default=False, verbose_name='건너뛰기 여부')),
                ('skip_reason', models.CharField(blank=True, max_length=200, verbose_name='건너뛰기 사유')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
            ],
            options={
                'verbose_name': '버스 수집 정보',
                'verbose_name_plural': '버스 수집 정보들',
                'ordering': ['-query_time'],
                'indexes': [models.Index(fields=['route_id', 'collection_date'], name='bus_info_bu_route_i_3d4112_idx'), models.Index(fields=['collection_date'], name='bus_info_bu_collect_c58564_idx')],
            },
        ),
        migrations.CreateModel(
            name='BusData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_no', models.CharField(max_length=20, verbose_name='차량 번호')),
                ('remain_seat_cnt', models.IntegerField(verbose_name='잔여 좌석 수')),
                ('station_seq', models.CharField(max_length=10, verbose_name='정류소 순번')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='bus_info.buscollection', verbose_name='수집 정보')),
            ],
            options={
                'verbose_name': '버스 데이터',
                'verbose_name_plural': '버스 데이터들',
                'ordering': ['plate_no'],
            },
        ),
    ]
